### ISSUE TITLE
Custom categories options.

### ISSUE THREAD

**Issue by Julioevm** [woodybury/rn-emoji-picker#2]
Awesome job, from all the emoji pickers that I've tried, this is the one I like the best!

There's a couple of suggestions I have. Would you consider making the available categories customizable? Like passing a list of the categories we want to show. What about being able to set a default category ? 

If you think these options could be useful, I could look into creating a MR.

**Comment by woodybury** [comment]
@Julioevm yes I think both are a great ideas. Feel free to make a PR if you got it otherwise I can get to it in the next week or so.

On an unrelated note, I'm thinking of switching the flat list dep to https://github.com/Shopify/flash-list b/c performance improvements w/ rending long lists. What are your thoughts? I could make the list provider optional (rn or  flash)....

**Comment by Julioevm** [comment]
I think it could be worth trying the flash-list, most emoji pickers suffer from performance, and it can probably help. Not sure though if its worth the extra complexity of choosing between both options if flash list is better, no external deps, but why choose worse performance? Anyway, my 2cents :smile:

**Comment by woodybury** [comment]
thanks for the feedback on flashlist, I've had good experience with it. Will see how it fairs here.

thanks for MR it's released https://www.npmjs.com/package/rn-emoji-picker @ 1.1.6
